# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ckumera <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/18 18:57:05 by ckumera           #+#    #+#              #
#    Updated: 2019/07/18 19:49:58 by ckumera          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: create

create:
	gcc -Werror -Wextra -Wall *.c
	mv a.out ft_display_file

clean:
	rm -rf *.o

fclean:
	rm -rf ft_display_file

re: fclean all
